"""empty message

Revision ID: 5b9b920835d0
Revises: 1b0775cd6b41
Create Date: 2024-01-29 12:12:24.296952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9b920835d0'
down_revision = '1b0775cd6b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre_fav', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('genre_fav_genres_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'genres', ['genre_id'], ['id'])
        batch_op.drop_column('genres_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre_fav', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('genre_fav_genres_id_fkey', 'genres', ['genres_id'], ['id'])
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###
