"""empty message

Revision ID: e9441f204397
Revises: bcc1ae17a03e
Create Date: 2024-01-27 21:21:35.191236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9441f204397'
down_revision = 'bcc1ae17a03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consoles_fav_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consoles_fav_association',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('console_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['console_id'], ['consoles.id'], name='consoles_fav_association_console_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='consoles_fav_association_user_id_fkey')
    )
    # ### end Alembic commands ###
